// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8TuT6tg0zUGiNEEOiw333umqNO3qYtfI',
    appId: '1:963495008261:web:8b919842659878589a246c',
    messagingSenderId: '963495008261',
    projectId: 'lifting-tracker-dev',
    authDomain: 'lifting-tracker-dev.firebaseapp.com',
    storageBucket: 'lifting-tracker-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs7dpgEIKjmkhi-hl6WrdqoXnI0EPtQEM',
    appId: '1:963495008261:android:485a07db82daf7399a246c',
    messagingSenderId: '963495008261',
    projectId: 'lifting-tracker-dev',
    storageBucket: 'lifting-tracker-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCczojPQAznfJiR6oqlKuRzF8fA5_yHYrc',
    appId: '1:963495008261:ios:4f27ae309cf0afb69a246c',
    messagingSenderId: '963495008261',
    projectId: 'lifting-tracker-dev',
    storageBucket: 'lifting-tracker-dev.firebasestorage.app',
    iosBundleId: 'com.luca.liftingtracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCczojPQAznfJiR6oqlKuRzF8fA5_yHYrc',
    appId: '1:963495008261:ios:55c93e1050edae9f9a246c',
    messagingSenderId: '963495008261',
    projectId: 'lifting-tracker-dev',
    storageBucket: 'lifting-tracker-dev.firebasestorage.app',
    iosBundleId: 'com.example.liftingTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8TuT6tg0zUGiNEEOiw333umqNO3qYtfI',
    appId: '1:963495008261:web:57d6b6bab2ea19039a246c',
    messagingSenderId: '963495008261',
    projectId: 'lifting-tracker-dev',
    authDomain: 'lifting-tracker-dev.firebaseapp.com',
    storageBucket: 'lifting-tracker-dev.firebasestorage.app',
  );
}
